import { IBuildOrder, BuildOrderStep, Food, Wood, Gold } from '../../model';
import { Vietnamese, Khmer, Franks, Berbers, Burmese, Chinese, Huns, Indians, Italians, Magyars, Malians, Mongols, Persians, Portuguese, Saracens, Slavs, Spanish, Teutons, Turks } from '../civs';
export class ScoutRushBuildOrder implements IBuildOrder {
  name: string = "Scout Rush";
  steps: BuildOrderStep[] = [
    { villagerCount: "3", details: "Queue villagers", idealTimeInSeconds: 2 },
    { villagerCount: "3", details: "Build 2 houses", footnotes: ["Then send to sheep"], idealTimeInSeconds: 4 },
    { villagerCount: "4", details: "Sheep", idealTimeInSeconds: 25, resources: [ new Food(4) ] },
    { villagerCount: "5", details: "Sheep", idealTimeInSeconds: 50, resources: [ new Food(5) ] },
    { villagerCount: "6", details: "Sheep", idealTimeInSeconds: 75, resources: [ new Food(6) ] },
    { villagerCount: "7", details: "Build lumber camp", footnotes: ["Then send to wood"], idealTimeInSeconds: 100, resources: [ new Wood(1), new Food(6) ] },
    { villagerCount: "8", details: "Wood", idealTimeInSeconds: 125, resources: [ new Wood(2), new Food(6) ] },
    { villagerCount: "9", details: "Wood", idealTimeInSeconds: 150, resources: [ new Wood(3), new Food(6) ] },
    { villagerCount: "10", details: "Build house and lure boar", idealTimeInSeconds: 175, resources: [ new Wood(3), new Food(7) ] },
    { villagerCount: "11", details: "Boar", idealTimeInSeconds: 200, resources: [ new Wood(3), new Food(8) ] },
    { villagerCount: "12", details: "Build mill", footnotes: ["Then send to berries"], idealTimeInSeconds: 225, resources: [ new Wood(3), new Food(9) ] },
    { villagerCount: "13", details: "Berries", idealTimeInSeconds: 250, resources: [ new Wood(3), new Food(10) ] },
    { villagerCount: "14", details: "Berries", footnotes: ["Send a boar/sheep villager to build house near 2nd boar"], idealTimeInSeconds: 275, resources: [ new Wood(3), new Food(10) ] },
    { villagerCount: "15", details: "Berries", idealTimeInSeconds: 300, resources: [ new Wood(3), new Food(11) ] },
    { villagerCount: "15", details: "Sheep/boar", footnotes: ["Lure 2nd boar with house villager."], idealTimeInSeconds: 300, resources: [ new Wood(3), new Food(12) ] },
    { villagerCount: "16", details: "Sheep/boar", idealTimeInSeconds: 325, resources: [ new Wood(3), new Food(13) ] },
    { villagerCount: "17", details: "Sheep/boar", idealTimeInSeconds: 350, footnotes: ["Build 2 farms with weak villagers"], resources: [ new Wood(3), new Food(14) ] },
    { villagerCount: "18", details: "Build lumber camp", footnotes: ["Then send to wood"], idealTimeInSeconds: 375, resources: [ new Wood(4), new Food(14) ] },
    { villagerCount: "19", details: "Wood", idealTimeInSeconds: 400, resources: [ new Wood(5), new Food(14) ] },
    { villagerCount: "20", details: "Wood", idealTimeInSeconds: 425, resources: [ new Wood(6), new Food(14) ] },
    { villagerCount: "21", details: "Wood", footnotes: [ "Research loom" ], idealTimeInSeconds: 470, resources: [ new Wood(7), new Food(14) ] },
    {
      villagerCount: "21", details: "Feudal Age",
      footnotes: ["Send 4 from food to wood.", "Send 1 to build barracks and a house."],
      idealTimeInSeconds: 580,
      ageUpValue: "II",
      resources: [ new Wood(11), new Food(10) ]
    },
    { villagerCount: "22", details: "Build stable and then houses. Train scouts.", idealTimeInSeconds: 605, resources: [ new Wood(11), new Food(10) ] },
    { villagerCount: "23", details: "Farm", footnotes: ["Build farms with idle villagers."], idealTimeInSeconds: 630, resources: [ new Wood(11), new Food(11) ] },
    { villagerCount: "24", details: "Farm", idealTimeInSeconds: 655, resources: [ new Wood(11), new Food(13) ] },
    { villagerCount: "25", details: "Farm", idealTimeInSeconds: 680, resources: [ new Wood(12), new Food(14) ] },
    { villagerCount: "26", details: "Farm", idealTimeInSeconds: 705, resources: [ new Wood(11), new Food(15) ] },
    { villagerCount: "27", details: "Farm", idealTimeInSeconds: 730, resources: [ new Wood(11), new Food(16) ] },
    { villagerCount: "28", details: "Farm", idealTimeInSeconds: 755, resources: [ new Wood(11), new Food(17) ] },
    { villagerCount: "29", details: "Wood", idealTimeInSeconds: 780, resources: [ new Wood(12), new Food(17) ] },
    { villagerCount: "30", details: "Wood", footnotes: ["Send a villager to build a range. Train skirms"], idealTimeInSeconds: 805, resources: [ new Wood(13), new Food(17) ] },
    { villagerCount: "31", details: "Build mining camp on gold", footnotes: ["Send 2 from berries to gold"], idealTimeInSeconds: 830, resources: [ new Wood(13), new Food(15), new Gold(3) ] },
    { villagerCount: "32", details: "Gold", idealTimeInSeconds: 855, resources: [ new Wood(13), new Food(15), new Gold(4) ] },
    { villagerCount: "33", details: "Gold", idealTimeInSeconds: 880, resources: [ new Wood(13), new Food(15), new Gold(5) ] },
    { villagerCount: "34", details: "Gold", idealTimeInSeconds: 905, resources: [ new Wood(13), new Food(15), new Gold(6) ] },
    { villagerCount: "35", details: "Gold", footnotes: ["Don't forget to build a blacksmith and get fletching."], idealTimeInSeconds: 930, resources: [ new Wood(13), new Food(15), new Gold(7) ] },
  ];
  finalTips = "Aim for castle age once you have over 6 scouts, 8 skirmishers and fletching.";
  recommendedCivs = [
    new Berbers(),
    new Burmese(),
    new Chinese(),
    new Franks(),
    new Huns(),
    new Indians(),
    new Italians(),
    new Khmer(),
    new Magyars(),
    new Malians(),
    new Mongols(),
    new Persians(),
    new Portuguese(),
    new Saracens(),
    new Slavs(),
    new Spanish(),
    new Teutons(),
    new Turks(),
    new Vietnamese()
  ];
}
